WELCOME_MESSAGE='Bot in fase di creazione :)'
ERROR_ADMIN_MESSAGE='Sei già nella lista degli admin'
ERROR_USER_MESSAGE='Sei già nella lista degli user'
CONFIRM_SEND_REQUEST='La tua richiesta è stata inviata'
NO_ROLE="Non hai l'autorizzazione necessaria per eseguire questo comando"
USER_ALREADY_IN_ADMIN="L'utente è già nella lista degli admin"
USER_ALREADY_IN_USER="L'utente è già nella lista degli user"
ADD_USER_ADMIN_CONFIRM='Utente inserito con successo nella lista degli admin'
ADD_USER_USER_CONFIRM='Utente inserito con successo nella lista degli user'
EMPTY_LIST='Lista vuota'
EMPTY_BACHECA='Bacheca vuota'
ADDED_MESSAGE='Messaggio inserito in bacheca'
NEW_MESSAGE='Nuovo messaggio in bacheca:\n'